### ISSUE TITLE
Provide feedback if Punk can't connect to Steam

### ISSUE THREAD

**Issue by Harcourt1** [scholtzm/punk#24]
Started the client and inputed my account, still loading for about an hour.
Nvm, needed to restart my wifi

**Comment by scholtzm** [comment]
It must have crashed, that's why it just kept "Loading". Hard to tell why though.

In case something like this happens again, open Dev tools with Alt+Command+I (or via menu bar) and the error will be logged there.

**edit.** Thinking about this once again, it was probably just trying to connect over and over again but some network error prevented it from being successful. Seems like the issue has been solved.

**Comment by scholtzm** [comment]
Reopening this.

I'd like to provide some feedback to user in case Punk can't even connect to Steam.

**Comment by Harcourt1** [comment]
Check my crash log patch, could do something like that.

**Comment by scholtzm** [comment]
The app in your case didn't really crash, it was just trying to connect over and over again but it wasn't providing any info about it. I'll think about how this can be improved later.

**Comment by scholtzm** [comment]
Punk now displays detailed info about disconnect status - specific error as well as retry count: https://github.com/scholtzm/punk/commit/d6357076a7283cb08903b83679e94edb3f4409ef

This can be closed now. Will be available in the next release.
